### ISSUE TITLE
Upload CSV Collection

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/WIPP-frontend#132]
**Description**
Currently CSV collections can only be generated as the output of a job. Due to the power of the Plots application, some users may want to upload a CSV file to view data in Plots.

**Proposal**
Add a method to create a new CSV collection from the WIPP frontend.

**Additional context**
Addition of this method can also aid in debugging plugins and functions that use CSV collections as input, since a pipeline will not need to be run in order to create a csv collection.

**Comment by MyleneSimon** [comment]
How big could the CSV files be in your opinion? 
Depending on that, we may have to use chunk upload to support this feature.

**Comment by Nicholas-Schaub** [comment]
Some of the larger files we handle are on the order of GBs.

Would it be difficult to re-use the current chunk upload code for images on csv's?

**Comment by MyleneSimon** [comment]
We will start by supporting regular upload, limited to 5Mb/file, see https://github.com/usnistgov/WIPP-backend/issues/110

@Samiasa :
The "New CSV Collection" interface will be similar to the "New Stitching Vector" one, except that user can select multiple files (restricted to .csv) and cannot input a comment. Errors coming from the REST API should be handled and displayed to the user. Success should redirect to the detail page of the newly created collection.
The CSV Collection detail should display "Uploaded" new to "Source Job" when there is no source job available (i.e the collection was uploaded).

**Comment by MyleneSimon** [comment]
Chunk upload of CSV files has been implemented (flowjs-based, similar to images).
Newly created CSV collections will now display list of CSV files.
