### ISSUE TITLE
Enable modifying parameters of a plugin before a workflow is launched

### ISSUE THREAD

**Issue by pbajcsy** [usnistgov/WIPP-frontend#138]
**Description**
Problem: It is impossible to delete a plugin or modify parameters of a plugin after closing a new task dialog although  a workflow has not been launched

**Proposal**
(1) Enable deleting a plugin (i.e., click to select a task/plugin and then provide an option to delete the plugin.
(2) Enable opening a dialog with parameters and editing parameters before a workflow is launched

**Additional context**
This feature will avoid costly mistakes during workflow construction and reduce the number of unused workflows.

**Comment by MyleneSimon** [comment]
Edit of workflow task parameters has been implemented.
Deletion of a task will be moved to a separate issue.
