### ISSUE TITLE
Set default numeric values in plugin schema

### ISSUE THREAD

**Issue by mohamedOuladi** [usnistgov/WIPP-frontend#205]
**Description**

Plugins developers should be able to set a default value for numeric fields in their plugins schemas. The user can then use the default value or modify it.

**Comment by MyleneSimon** [comment]
@mohamedOuladi This is already supported, see for example the default values in the MIST manifest: https://github.com/usnistgov/MIST/blob/1fd6c93fd2e2886a6230dde378c6c45854d09bc3/wipp-plugin.json#L324

**Comment by mohamedOuladi** [comment]
thanks!
